# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Skillplot
# subtitle: Namaste
description: >- # this means to ignore newlines until "baseurl:"
  Because knowledge belongs to humanity.
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "" # the base hostname & protocol for your site
#syllabus: ""
githubdir: "skillplot.github.io"
# url: "https://mangalbhaskar.com" # the base hostname & protocol for your site, e.g. http://example.com
copyright: © mangalbhaskar 2022. All Rights Reserved.

# Author/user information
authors:
  name: mangalbhaskar
  display_name: Mangal

#email: 
twitter_username: mangalbhaskar
# github_username:  "skillplot/skillplot.github.io"
github_username:  mangalbhaskar
authorurl: "https://mangalbhaskar.com"
orcid_id: 0000-0002-8126-3528
#google_scholar_id:
address: India


words_per_minute: 200

# Pagination 
paginate: 5 # amount of posts to show
paginate_path: /page:num/
# paginate_path: /blog/page:num/
timezone: Asia/Kolkata # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include:
  - .htaccess
  - _pages
  - _posts
  - _images
  - _css

exclude: 
  - node_modules
  - changelog.md
  - LICENSE.txt
  - README.md
  - CREDITS.md
  - Gemfile
  - Gemfile.lock
  - vendor

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""

plugings_dir:
  - jekyll-sitemap
#exclude: []
