# Site
name: "Skillplot"
title: "Skillplot"
# subtitle: Namaste
description: >- # this means to ignore newlines until "baseurl:"
  Because knowledge belongs to humanity.
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
url: https://skillplot.github.io
# baseurl: skillplot.github.io
# baseurl: "" # the subpath of your site, e.g. /blog/
#url: "" # the base hostname & protocol for your site
#syllabus: ""
githubdir: "skillplot.github.io"
# url: "https://mangalbhaskar.com" # the base hostname & protocol for your site, e.g. http://example.com
copyright: © mangalbhaskar 2022. All Rights Reserved.

# Author/user information
authors:
  name: mangalbhaskar
  display_name: Mangal

#email: 
twitter_username: mangalbhaskar
# github_username:  "skillplot/skillplot.github.io"
github_username:  mangalbhaskar
authorurl: "https://mangalbhaskar.com"
orcid_id: 0000-0002-8126-3528
#google_scholar_id:
address: India

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  # - jekyll-include-cache

# mimic GitHub Pages with --safe
# whitelist:
#   - jekyll-paginate
#   - jekyll-sitemap
#   - jekyll-gist
#   - jekyll-feed
#   - jekyll-seo-tag
#   - jekyll-archives
#   # - jekyll-include-cache

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

words_per_minute: 200

# Pagination 
paginate: 5 # amount of posts to show
paginate_path: /page:num/
# paginate_path: /blog/page:num/
timezone: Asia/Kolkata # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

include:
  - .htaccess
  - _pages
  - _posts
  - _images
  - _css

exclude: 
  - node_modules
  - changelog.md
  - LICENSE.txt
  - README.md
  - CREDITS.md
  - Gemfile
  - Gemfile.lock
  - vendor

comments:
  provider: staticman_v2
  staticman:
    branch: master
    endpoint: https://skillplot-staticman.herokuapp.com/v3/entry/github

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""

# search                   : # true, false (default)
# search_full_content      : # true, false (default)
# search_provider          : # lunr (default), algolia, google
# algolia:
#   application_id         : # YOUR_APPLICATION_ID
#   index_name             : # YOUR_INDEX_NAME
#   search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
#   powered_by             : # true (default), false
# google:
#   search_engine_id       : # YOUR_SEARCH_ENGINE_ID
#   instant_search         : # false (default), true
# # SEO Related
# google_site_verification :
# bing_site_verification   :
# yandex_site_verification :
# naver_site_verification  :

# plugings_dir:
#   - jekyll-sitemap
#exclude: []
